name: CI

on:
  pull_request:
    branches: [ develop ]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      # hub コマンドをインストールする
      - name: install hub
        uses: geertvdc/setup-hub@v1.0.0

      # マージされたheadブランチからreleaseブランチへPRを出す
      # headブランチにHOTFIXラベルがついてたらmasterへのPRにするとか
      # レビュワーを自動で入れるとかもやりたい
      - name: Create Pull Request
        run: |
          hub pull-request -m "（ステージングイン済み）${{github.event.pull_request.title}}" -m "${{github.event.pull_request.body}}" -b release -h ${{github.event.pull_request.head.ref}} -l "PR:release"
