# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  pull_request:
    branches: [ develop ]
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # hub コマンドをインストールする
      - name: install hub
        uses: geertvdc/setup-hub@v1.0.0

      # マージされたfeatureブランチをチェックアウトする
      - name: checkout feature
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub pull-request -m "${{github.event.pull_request.title}}" -b release -h ${{github.event.pull_request.head.ref}} -l "PR:draft"
